### Fetch countries
GET https://de1.api.radio-browser.info/json/countries?order=stationcount&reverse=true&limit=5

### Fetch genres (tags)
GET https://de1.api.radio-browser.info/json/tags?order=stationcount&reverse=true&limit=5

### Search by tag (Example: Dance)
GET https://de1.api.radio-browser.info/json/stations/search?tag=dance&order=clickcount&limit=5&reverse=true&hidebroken=true&offset=0

### Search by country (Example: Canada)
# Note: The country name must start with an uppercase letter (e.g., 'Canada', not 'canada')
GET https://de1.api.radio-browser.info/json/stations/search?country=Canada&order=clickcount&limit=5&reverse=true&hidebroken=true&offset=0
